### ISSUE TITLE
Text not visible in textfield when using dark theme

### ISSUE THREAD

**Issue by ivarnakken** [webkom/lego-editor#374]
When using the dark theme, the textfields in the link functionality of the text editor has the color white. This makes the text impossible to read, at least without highlighting it ... 

The images below illustrate the issue.

<img src="https://user-images.githubusercontent.com/69514187/140817284-8769adb9-6b86-4c17-93b0-4998554b57e3.png" width="500" />
<img src="https://user-images.githubusercontent.com/69514187/140817289-d43ad588-ce36-4066-a1e5-d0e5f6ec1fc2.png" width="500" />

**Comment by LieuMai** [comment]
Can you assign me for this issue?

**Comment by ivarnakken** [comment]
Resolved by https://github.com/webkom/lego-editor/pull/900
