### ISSUE TITLE
Multiple txt-sizes on the same line

### ISSUE THREAD

**Issue by iselinee** [webkom/lego-editor#52]
Can't have more than one text size on the same line. If you first write something in h1, then want to write the rest in h4, everything turns to h4.

![Skjermbilde 2019-10-09 kl  19 05 18](https://user-images.githubusercontent.com/43182013/66503778-26fd3d00-eac8-11e9-965c-4fbcbd0e56ef.png)

**Comment by LudvigHz** [comment]
This is intended, and there is no way to change the behavior, so closing this.
